print('helloworld')
print('hello')
print('helloworld')
print('lets conflict ok')
print('helloworld')
print('hello')
print('helloworld')
print('hello')
print('helloworld')
print('hello')
print('lets fight')
