print('helloworld')
print('hello')
print('helloworld')
print('hell7 is the best')
print('helloworld')
print('hello')
print('helloworld')
print('hello')
print('helloworld')
print('hello')
print('lets fight')