print('helloworld')
print('hello')
print('helloworld')
print('hell7 is the best ita osk') # this is done
print('helloworld')
print('hello')
print('helloworld')
print('hello')
print('helloworld')
print('hello')
print('lets fight')
